name       : ruby-gssapi
version    : 1.2.0
release    : 3
source     :
    - https://rubygems.org/downloads/gssapi-1.2.0.gem : 3d0e3222f36532c1ab3b7eaab171ad4245889edc5439a5483ff714999cb62349
license    : MIT
component  : programming.ruby
summary    : RubyGem - gssapi
description: |
    A FFI wrapper around the system GSSAPI library. Please make sure and read the Yard docs or standard GSSAPI documentation if you have any questions. There is also a class called GSSAPI::Simple that wraps many of the common features used for GSSAPI.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby-ffi
install    : |
    %gem_install
